// Multilingual support for Tesla markets
export type SupportedLanguage = 'en' | 'zh' | 'de' | 'fr' | 'es' | 'it' | 'ja' | 'ko' | 'nl' | 'no' | 'sv' | 'da' | 'pt' | 'tr';

export const supportedLanguages: { code: SupportedLanguage; name: string; flag: string }[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'no', name: 'Norsk', flag: '🇳🇴' },
  { code: 'sv', name: 'Svenska', flag: '🇸🇪' },
  { code: 'da', name: 'Dansk', flag: '🇩🇰' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
];

export const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // App Title
    'app.title': 'Tesla Delivery Companion',
    'app.subtitle': 'Professional Pre-Delivery Inspection System',
    
    // Phase Headers
    'phase.onDelivery.title': 'Phase 1: On Delivery Inspection',
    'phase.onDelivery.description': 'Visual inspection items that can be checked while the vehicle is stationary',
    'phase.testDrive.title': 'Phase 2: Test Drive Inspection',
    'phase.testDrive.description': 'Dynamic testing issues that appear during driving (<100km)',
    
    // Status
    'status.pending': 'Pending',
    'status.completed': 'Completed',
    'status.approved': 'Approved',
    'status.waiting': 'Waiting',
    'status.failed': 'Failed',
    'status.passed': 'Passed',
    
    // Actions
    'action.approve': 'Approve Phase',
    'action.complete': 'Complete Inspection',
    'action.addEvidence': 'Add Evidence',
    'action.takePhoto': 'Take Photo',
    'action.recordVideo': 'Record Video',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.next': 'Next',
    'action.previous': 'Previous',
    
    // Forms
    'form.orderNumber': 'Order Number',
    'form.customerName': 'Customer Name',
    'form.customerEmail': 'Customer Email',
    'form.repName': 'Tesla Representative Name',
    'form.repEmail': 'Tesla Representative Email',
    'form.notes': 'Notes',
    'form.signature': 'Digital Signature',
    
    // Evidence
    'evidence.photos': 'Photos',
    'evidence.video': 'Video',
    'evidence.required': 'Evidence Required',
    'evidence.maxPhotos': 'Up to 5 photos',
    'evidence.maxVideo': '2-minute video',
    'evidence.limitReached': 'Evidence limit reached',
    
    // Errors
    'error.generic': 'An error occurred. Please try again.',
    'error.network': 'Network error. Please check your connection.',
    'error.fileSize': 'File size exceeds limit (50MB)',
    'error.filetype': 'Invalid file type',
    'error.photoLimit': 'Maximum 5 photos allowed per item',
    'error.videoLimit': 'Only one video allowed per item',
    'error.required': 'This field is required',
    'error.invalidEmail': 'Please enter a valid email address',
    
    // Success Messages
    'success.phasecompleted': 'Phase completed successfully',
    'success.evidenceuploaded': 'Evidence uploaded successfully',
    'success.inspectioncompleted': 'Inspection completed and report generated',
    'success.emailsent': 'Report sent via email',
    'success.repValidated': 'Tesla representative information validated',
    
    // Progress
    'progress.items': 'items',
    'progress.failed': 'failed',
    'progress.completed': 'completed',
    'progress.total': 'total',
    
    // Tesla Representative
    'form.teslaRepresentative': 'Tesla Representative Information',
    'form.teslaRepresentativeDesc': 'Enter the Tesla representative details for this delivery inspection',
    'placeholder.repName': 'Enter representative full name',
    'placeholder.repEmail': 'representative@tesla.com',
    'error.nameLength': 'Name must be at least 2 characters',
    'error.mustBeTeslaEmail': 'Must be a Tesla email address (@tesla.com)',
    'warning.externalEmail': 'Warning: External email address detected',
    'status.verified': 'Verified',
    'status.incomplete': 'Incomplete',
    'info.repWillReceiveCopy': 'Representative will receive a copy of all inspection reports',
    'error.validation': 'Validation error',
    'error.unauthorized': 'Unauthorized access',
    'error.forbidden': 'Access forbidden',
    'error.notfound': 'Not found',
    'error.rateLimit': 'Too many requests, please try again later',
    'error.server': 'Server error, please try again',
    'error.timeout': 'Request timeout',
    'error.permissions': 'Permission denied',
    'error.title': 'Error',
    'action.retry': 'Retry',
  },
  
  zh: {
    'app.title': '特斯拉交付伴侣',
    'app.subtitle': '专业交付前检查系统',
    'phase.onDelivery.title': '第一阶段：交付检查',
    'phase.onDelivery.description': '车辆静止时可检查的视觉检查项目',
    'phase.testDrive.title': '第二阶段：试驾检查',
    'phase.testDrive.description': '驾驶过程中出现的动态测试问题（<100公里）',
    'status.pending': '待处理',
    'status.completed': '已完成',
    'status.approved': '已批准',
    'status.waiting': '等待中',
    'status.failed': '失败',
    'status.passed': '通过',
    'action.approve': '批准阶段',
    'action.complete': '完成检查',
    'action.addEvidence': '添加证据',
    'action.takePhoto': '拍照',
    'action.recordVideo': '录制视频',
    'form.orderNumber': '订单号',
    'form.customerName': '客户姓名',
    'form.customerEmail': '客户邮箱',
    'form.repName': '特斯拉代表姓名',
    'form.repEmail': '特斯拉代表邮箱',
    'evidence.maxPhotos': '最多5张照片',
    'evidence.maxVideo': '2分钟视频',
    'error.generic': '发生错误，请重试。',
    'error.network': '网络错误，请检查连接。',
    'error.fileSize': '文件大小超出限制（50MB）',
    'success.phasecompleted': '阶段完成成功',
    'success.evidenceuploaded': '证据上传成功',
  },
  
  de: {
    'app.title': 'Tesla Auslieferungsbegleiter',
    'app.subtitle': 'Professionelles Vorablieferungs-Prüfsystem',
    'phase.onDelivery.title': 'Phase 1: Auslieferungsinspektion',
    'phase.onDelivery.description': 'Sichtprüfungselemente bei stehendem Fahrzeug',
    'phase.testDrive.title': 'Phase 2: Probefahrt-Inspektion',
    'phase.testDrive.description': 'Dynamische Testprobleme während der Fahrt (<100km)',
    'status.pending': 'Ausstehend',
    'status.completed': 'Abgeschlossen',
    'status.approved': 'Genehmigt',
    'action.approve': 'Phase genehmigen',
    'action.complete': 'Inspektion abschließen',
    'form.orderNumber': 'Bestellnummer',
    'form.customerName': 'Kundenname',
    'form.repName': 'Tesla-Vertreter Name',
    'evidence.maxPhotos': 'Bis zu 5 Fotos',
    'evidence.maxVideo': '2-Minuten-Video',
    'error.generic': 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    'success.phasecompleted': 'Phase erfolgreich abgeschlossen',
  },
  
  fr: {
    'app.title': 'Compagnon de Livraison Tesla',
    'app.subtitle': 'Système d\'Inspection Professionnel Avant Livraison',
    'phase.onDelivery.title': 'Phase 1: Inspection à la Livraison',
    'phase.onDelivery.description': 'Éléments d\'inspection visuelle avec véhicule immobile',
    'phase.testDrive.title': 'Phase 2: Inspection Essai Routier',
    'phase.testDrive.description': 'Problèmes de test dynamique pendant la conduite (<100km)',
    'status.pending': 'En attente',
    'status.completed': 'Terminé',
    'status.approved': 'Approuvé',
    'action.approve': 'Approuver la phase',
    'action.complete': 'Terminer l\'inspection',
    'form.orderNumber': 'Numéro de commande',
    'form.customerName': 'Nom du client',
    'form.repName': 'Nom du représentant Tesla',
    'evidence.maxPhotos': 'Jusqu\'à 5 photos',
    'evidence.maxVideo': 'Vidéo de 2 minutes',
    'error.generic': 'Une erreur s\'est produite. Veuillez réessayer.',
    'success.phasecompleted': 'Phase terminée avec succès',
  },
  
  es: {
    'app.title': 'Compañero de Entrega Tesla',
    'app.subtitle': 'Sistema Profesional de Inspección Pre-Entrega',
    'phase.onDelivery.title': 'Fase 1: Inspección en Entrega',
    'phase.onDelivery.description': 'Elementos de inspección visual con vehículo estacionario',
    'phase.testDrive.title': 'Fase 2: Inspección de Prueba de Manejo',
    'phase.testDrive.description': 'Problemas de prueba dinámica durante la conducción (<100km)',
    'status.pending': 'Pendiente',
    'status.completed': 'Completado',
    'status.approved': 'Aprobado',
    'action.approve': 'Aprobar fase',
    'action.complete': 'Completar inspección',
    'form.orderNumber': 'Número de pedido',
    'form.customerName': 'Nombre del cliente',
    'form.repName': 'Nombre del representante Tesla',
    'evidence.maxPhotos': 'Hasta 5 fotos',
    'evidence.maxVideo': 'Video de 2 minutos',
    'error.generic': 'Ocurrió un error. Por favor intente nuevamente.',
    'success.phasecompleted': 'Fase completada exitosamente',
  },
  
  it: {
    'app.title': 'Compagno di Consegna Tesla',
    'app.subtitle': 'Sistema Professionale di Ispezione Pre-Consegna',
    'phase.onDelivery.title': 'Fase 1: Ispezione alla Consegna',
    'phase.onDelivery.description': 'Elementi di ispezione visiva con veicolo fermo',
    'phase.testDrive.title': 'Fase 2: Ispezione Test Drive',
    'phase.testDrive.description': 'Problemi di test dinamico durante la guida (<100km)',
    'status.pending': 'In attesa',
    'status.completed': 'Completato',
    'status.approved': 'Approvato',
    'action.approve': 'Approva fase',
    'action.complete': 'Completa ispezione',
    'form.orderNumber': 'Numero ordine',
    'form.customerName': 'Nome cliente',
    'form.repName': 'Nome rappresentante Tesla',
    'evidence.maxPhotos': 'Fino a 5 foto',
    'evidence.maxVideo': 'Video di 2 minuti',
    'error.generic': 'Si è verificato un errore. Riprova.',
    'success.phasecompleted': 'Fase completata con successo',
  },
  
  ja: {
    'app.title': 'テスラ納車コンパニオン',
    'app.subtitle': 'プロフェッショナル納車前検査システム',
    'phase.onDelivery.title': 'フェーズ1：納車時検査',
    'phase.onDelivery.description': '車両停止時に確認可能な外観検査項目',
    'phase.testDrive.title': 'フェーズ2：試乗検査',
    'phase.testDrive.description': '運転中に現れる動的テスト問題（<100km）',
    'status.pending': '保留中',
    'status.completed': '完了',
    'status.approved': '承認済み',
    'action.approve': 'フェーズを承認',
    'action.complete': '検査を完了',
    'form.orderNumber': '注文番号',
    'form.customerName': '顧客名',
    'form.repName': 'テスラ担当者名',
    'evidence.maxPhotos': '最大5枚の写真',
    'evidence.maxVideo': '2分間の動画',
    'error.generic': 'エラーが発生しました。もう一度お試しください。',
    'success.phasecompleted': 'フェーズが正常に完了しました',
  },
  
  ko: {
    'app.title': '테슬라 인도 컴패니언',
    'app.subtitle': '전문 인도 전 검사 시스템',
    'phase.onDelivery.title': '1단계: 인도 시 검사',
    'phase.onDelivery.description': '차량 정지 상태에서 확인 가능한 외관 검사 항목',
    'phase.testDrive.title': '2단계: 시승 검사',
    'phase.testDrive.description': '주행 중 나타나는 동적 테스트 문제 (<100km)',
    'status.pending': '대기 중',
    'status.completed': '완료',
    'status.approved': '승인됨',
    'action.approve': '단계 승인',
    'action.complete': '검사 완료',
    'form.orderNumber': '주문 번호',
    'form.customerName': '고객명',
    'form.repName': '테슬라 담당자명',
    'evidence.maxPhotos': '최대 5장의 사진',
    'evidence.maxVideo': '2분 동영상',
    'error.generic': '오류가 발생했습니다. 다시 시도해주세요.',
    'success.phasecompleted': '단계가 성공적으로 완료되었습니다',
  },
  
  nl: {
    'app.title': 'Tesla Afleveringscompagnon',
    'app.subtitle': 'Professioneel Pre-Aflevering Inspectiesysteem',
    'phase.onDelivery.title': 'Fase 1: Afleveringsinspectie',
    'phase.onDelivery.description': 'Visuele inspectie-elementen bij stilstaand voertuig',
    'phase.testDrive.title': 'Fase 2: Proefrit Inspectie',
    'phase.testDrive.description': 'Dynamische testproblemen tijdens het rijden (<100km)',
    'status.pending': 'In behandeling',
    'status.completed': 'Voltooid',
    'status.approved': 'Goedgekeurd',
    'action.approve': 'Fase goedkeuren',
    'action.complete': 'Inspectie voltooien',
    'form.orderNumber': 'Bestelnummer',
    'form.customerName': 'Klantnaam',
    'form.repName': 'Tesla vertegenwoordiger naam',
    'evidence.maxPhotos': 'Tot 5 foto\'s',
    'evidence.maxVideo': '2-minuten video',
    'error.generic': 'Er is een fout opgetreden. Probeer het opnieuw.',
    'success.phasecompleted': 'Fase succesvol voltooid',
  },
  
  no: {
    'app.title': 'Tesla Leveringsledsager',
    'app.subtitle': 'Profesjonelt Før-Levering Inspeksjonssystem',
    'phase.onDelivery.title': 'Fase 1: Leveringsinspeksjon',
    'phase.onDelivery.description': 'Visuelle inspeksjonselementer med stående kjøretøy',
    'phase.testDrive.title': 'Fase 2: Testkjøring Inspeksjon',
    'phase.testDrive.description': 'Dynamiske testproblemer under kjøring (<100km)',
    'status.pending': 'Venter',
    'status.completed': 'Fullført',
    'status.approved': 'Godkjent',
    'action.approve': 'Godkjenn fase',
    'action.complete': 'Fullfør inspeksjon',
    'form.orderNumber': 'Ordrenummer',
    'form.customerName': 'Kundenavn',
    'form.repName': 'Tesla representant navn',
    'evidence.maxPhotos': 'Opptil 5 bilder',
    'evidence.maxVideo': '2-minutters video',
    'error.generic': 'En feil oppstod. Vennligst prøv igjen.',
    'success.phasecompleted': 'Fase fullført med suksess',
  },
  
  sv: {
    'app.title': 'Tesla Leveransledsagare',
    'app.subtitle': 'Professionellt För-Leverans Inspektionssystem',
    'phase.onDelivery.title': 'Fas 1: Leveransinspektionen',
    'phase.onDelivery.description': 'Visuella inspektionselement med stillastående fordon',
    'phase.testDrive.title': 'Fas 2: Provkörningsinspektionen',
    'phase.testDrive.description': 'Dynamiska testproblem under körning (<100km)',
    'status.pending': 'Väntande',
    'status.completed': 'Slutförd',
    'status.approved': 'Godkänd',
    'action.approve': 'Godkänn fas',
    'action.complete': 'Slutför inspektion',
    'form.orderNumber': 'Ordernummer',
    'form.customerName': 'Kundnamn',
    'form.repName': 'Tesla representant namn',
    'evidence.maxPhotos': 'Upp till 5 bilder',
    'evidence.maxVideo': '2-minuters video',
    'error.generic': 'Ett fel inträffade. Vänligen försök igen.',
    'success.phasecompleted': 'Fas slutförd framgångsrikt',
  },
  
  da: {
    'app.title': 'Tesla Leveringsledsager',
    'app.subtitle': 'Professionelt Før-Levering Inspektionssystem',
    'phase.onDelivery.title': 'Fase 1: Leveringsinspektionen',
    'phase.onDelivery.description': 'Visuelle inspektionselementer med stillestående køretøj',
    'phase.testDrive.title': 'Fase 2: Prøvekørsel Inspektion',
    'phase.testDrive.description': 'Dynamiske testproblemer under kørsel (<100km)',
    'status.pending': 'Afventende',
    'status.completed': 'Fuldført',
    'status.approved': 'Godkendt',
    'action.approve': 'Godkend fase',
    'action.complete': 'Fuldfør inspektion',
    'form.orderNumber': 'Ordrenummer',
    'form.customerName': 'Kundenavn',
    'form.repName': 'Tesla repræsentant navn',
    'evidence.maxPhotos': 'Op til 5 billeder',
    'evidence.maxVideo': '2-minutters video',
    'error.generic': 'Der opstod en fejl. Prøv venligst igen.',
    'success.phasecompleted': 'Fase fuldført med succes',
  },
  
  pt: {
    'app.title': 'Companheiro de Entrega Tesla',
    'app.subtitle': 'Sistema Profissional de Inspeção Pré-Entrega',
    'phase.onDelivery.title': 'Fase 1: Inspeção na Entrega',
    'phase.onDelivery.description': 'Elementos de inspeção visual com veículo parado',
    'phase.testDrive.title': 'Fase 2: Inspeção Test Drive',
    'phase.testDrive.description': 'Problemas de teste dinâmico durante a condução (<100km)',
    'status.pending': 'Pendente',
    'status.completed': 'Concluído',
    'status.approved': 'Aprovado',
    'action.approve': 'Aprovar fase',
    'action.complete': 'Completar inspeção',
    'form.orderNumber': 'Número do pedido',
    'form.customerName': 'Nome do cliente',
    'form.repName': 'Nome do representante Tesla',
    'evidence.maxPhotos': 'Até 5 fotos',
    'evidence.maxVideo': 'Vídeo de 2 minutos',
    'error.generic': 'Ocorreu um erro. Tente novamente.',
    'success.phasecompleted': 'Fase concluída com sucesso',
  },
  
  tr: {
    'app.title': 'Tesla Teslimat Arkadaşı',
    'app.subtitle': 'Profesyonel Teslimat Öncesi İnceleme Sistemi',
    'phase.onDelivery.title': 'Faz 1: Teslimat İncelemesi',
    'phase.onDelivery.description': 'Araç durur haldeyken kontrol edilebilen görsel inceleme öğeleri',
    'phase.testDrive.title': 'Faz 2: Test Sürüşü İncelemesi',
    'phase.testDrive.description': 'Sürüş sırasında ortaya çıkan dinamik test sorunları (<100km)',
    'status.pending': 'Beklemede',
    'status.completed': 'Tamamlandı',
    'status.approved': 'Onaylandı',
    'action.approve': 'Fazı onayla',
    'action.complete': 'İncelemeyi tamamla',
    'form.orderNumber': 'Sipariş numarası',
    'form.customerName': 'Müşteri adı',
    'form.repName': 'Tesla temsilcisi adı',
    'evidence.maxPhotos': '5 fotoğrafa kadar',
    'evidence.maxVideo': '2 dakikalık video',
    'error.generic': 'Bir hata oluştu. Lütfen tekrar deneyin.',
    'success.phasecompleted': 'Faz başarıyla tamamlandı',
  },
};

// Translation hook
export function useTranslation(language: SupportedLanguage = 'en') {
  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };
  
  return { t, language };
}

// Language detection from browser
export function detectLanguage(): SupportedLanguage {
  if (typeof window === 'undefined') return 'en';
  
  const browserLang = navigator.language.split('-')[0] as SupportedLanguage;
  const supportedCodes = supportedLanguages.map(l => l.code);
  
  return supportedCodes.includes(browserLang) ? browserLang : 'en';
}